# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-8f8ddab0-ba65-4015-a65f-35fbd00385a5";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-8f8ddab0-ba65-4015-a65f-35fbd00385a5".device = "/dev/disk/by-uuid/8f8ddab0-ba65-4015-a65f-35fbd00385a5";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C5AB-57E6";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-26fcc57f-6de2-4ea0-9c1e-9411b537d0ae"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
