#!/bin/sh
# Usage: brightness up|down|set <value>

CMD="${1:-up}"

case "$CMD" in
    up)   brightnessctl set 5%+ ;;
    down) brightnessctl set 5%- ;;
    set)  brightnessctl set "${2:-50}%" ;;
esac

pct=$(brightnessctl g)
max=$(brightnessctl m)
pct=$((pct * 100 / max))

indicator "Brightness Indicator" "Brightness" "${pct}%"
