#!/bin/sh
# Usage: hypridle on|off|toggle

CMD="${1:-toggle}"
HYPRIDLE=$(command -v hypridle)

case "$CMD" in
    on)
        if ! pgrep -x hypridle >/dev/null; then $HYPRIDLE & fi
        text="Enabled" ;;
    off)
        pkill -x hypridle 2>/dev/null || true
        text="Disabled" ;;
    *)
        if pgrep -x hypridle >/dev/null; then
            pkill -x hypridle 2>/dev/null || true
            text="Disabled"
        else
            $HYPRIDLE &
            text="Enabled"
        fi ;;
esac

indicator "Hypridle Indicator" "Idle Inhibit" "$text"
